'use client';

import React from 'react';
import { Container, Title, Text, Button, Card, Stack, Group, Box, Badge } from '@mantine/core';
import { IconArrowRight, IconSparkles } from '@tabler/icons-react';
import Link from 'next/link';

/**
 * Generated by PM33 Content Factory
 * Source: peer-driven-pm-challenge-post
 * Generated: 2025-08-24
 */

export default function LinkedinPostPeerDrivenPmChallengePage() {
  return (
    <div className="marketing-context">
      <Box style={{ minHeight: '100vh', backgroundColor: 'var(--mantine-color-gray-0)' }}>
        
        {/* Hero Section */}
        <Box 
          style={{ 
            position: 'relative',
            padding: '4rem 0',
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            overflow: 'hidden',
            color: 'white'
          }}
        >
          <Container size="xl">
            <Stack align="center" gap={32}>
              <Badge 
                size="lg" 
                variant="light"
                color="white"
                leftSection={<IconSparkles size={16} />}
              >
                Community Insights
              </Badge>
              
              <Stack align="center" gap={24}>
                <Title 
                  order={1} 
                  size="3rem"
                  ta="center"
                  lh={1.1}
                  style={{ 
                    fontWeight: 900,
                    color: 'white',
                    maxWidth: 900,
                    textShadow: '0 2px 4px rgba(0,0,0,0.1)'
                  }}
                >
                  LinkedIn Post: Peer-Driven PM Challenge
                </Title>
                
                <Text size="xl" ta="center" maw={700} lh={1.6} style={{ opacity: 0.95 }}>
                  "I'm curious—what's your favorite way to keep your product roadmap collaborative instead of just another deck that collects dust?"
                </Text>

                <Group gap={24} mt={32}>
                  <Button 
                    component={Link}
                    href="/pricing"
                    size="xl"
                    variant="white"
                    color="dark"
                    rightSection={<IconArrowRight size={20} />}
                    style={{ 
                      minWidth: 200,
                      fontWeight: 600
                    }}
                  >
                    Start Free Trial
                  </Button>
                  <Button 
                    component={Link}
                    href="/strategic-intelligence"
                    size="xl"
                    variant="outline"
                    color="white"
                    rightSection={<IconSparkles size={20} />}
                    style={{ minWidth: 180 }}
                  >
                    See Live Demo
                  </Button>
                </Group>
              </Stack>
            </Stack>
          </Container>
        </Box>

        {/* Content Section */}
        <Box py={96} bg="white">
          <Container size="xl">
            <div className="content-factory-article" style={{
              fontSize: '18px',
              lineHeight: '1.7',
              color: 'var(--mantine-color-dark-8)'
            }}>
              <Title order={1} size="2.5rem" mb={24} c="dark">LinkedIn Post: Peer-Driven PM Challenge</Title>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Post Title: What's Your Favorite Way to Keep Product Roadmaps Actually Collaborative?</Title>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Opening Hook</Title>
              <Text mb={16} lh={1.7}>"I'm curious—what's your favorite way to keep your product roadmap collaborative instead of just another deck that collects dust?"</Text>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Invite Stories and Debate</Title>
              <Text mb={16} lh={1.7}>"Let's swap tactics—here's what our PM circle shared last week:</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>→ Some swear by live roadmap reviews with rotating stakeholder leads</Text>
              <Text mb={16} lh={1.7}>→ Others do async voting on feature priorities using simple polls</Text>
              <Text mb={16} lh={1.7}>→ A few have moved to 'roadmap office hours' where anyone can drop in with questions"</Text>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Share Real Peer Examples</Title>
              <Text mb={16} lh={1.7}>"My favorite so far came from @SarahPM at a Series B startup: 'We treat our roadmap like a Wikipedia page—anyone can suggest edits, but changes require peer review from 2+ PMs plus engineering lead approval.'"</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Poll I ran in our PM Slack:</Text>
              <Text component="li" mb={8}>40% use live collaborative sessions</Text>
              <Text component="li" mb={8}>35% prefer async feedback loops  </Text>
              <Text component="li" mb={8}>25% mix both approaches</Text>
              <Text component="li" mb={8}>Surprising: Only 60% actually measure if their 'collaborative' process works!"</Text>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Build Conversation, Not Conversion</Title>
              <Text mb={16} lh={1.7}>"Reply with a challenge you're facing with roadmap collaboration—I'm thinking about facilitating a small group discussion for PMs dealing with similar stakeholder dynamics."</Text>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Value-First Table (Community-Sourced)</Title>
              <Text mb={16} lh={1.7}>| Community-Sourced Approach | Best For | Pro Tip |</Text>
              <Text mb={16} lh={1.7}>|----------------------------|----------|---------|</Text>
              <Text mb={16} lh={1.7}>| Quarterly roadmap hackathons | Distributed teams | Start with async prep, end with live voting |</Text>
              <Text mb={16} lh={1.7}>| Weekly roadmap office hours | Stakeholder-heavy orgs | Rotate facilitator each session |</Text>
              <Text mb={16} lh={1.7}>| Living roadmap wiki | Fast-moving startups | Version control + comment threads |</Text>
              <Text mb={16} lh={1.7}>| Feature request triage calls | Customer-driven products | Include support team insights |</Text>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Include Open Invitation</Title>
              <Text mb={16} lh={1.7}>"If you'd like to co-author a collaborative roadmapping resource or host a local PM conversation about stakeholder alignment, drop a comment or DM! Always looking for peers who want to figure this stuff out together."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Tag active community contributors:</Text>
              <Text mb={16} lh={1.7}>"Tagging @ProductAlly @PMInsights @CollaborativePM—you've all shared great roadmap tactics before. What's working for your teams lately?"</Text>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Best Practices Implementation:</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>Community-First Elements:</Text>
              <Text component="li" mb={8}>Opens with genuine curiosity, not expertise claim</Text>
              <Text component="li" mb={8}>Shares peer examples with attribution</Text>
              <Text component="li" mb={8}>Includes poll data from community input</Text>
              <Text component="li" mb={8}>Offers to facilitate peer discussions</Text>
              <Text component="li" mb={8}>Tags people known for community building</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Authentic Voice:</Text>
              <Text component="li" mb={8}>"I'm curious" instead of "I know"</Text>
              <Text component="li" mb={8}>"Let's swap tactics" instead of "Here's how to do it"</Text>
              <Text component="li" mb={8}>"Favorite so far" shows ongoing learning</Text>
              <Text component="li" mb={8}>"Figure this stuff out together" positions as peer, not expert</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>PM33 Integration (Subtle):</Text>
              <Text component="li" mb={8}>No direct PM33 mention in this post</Text>
              <Text component="li" mb={8}>If commenters ask about tools, include PM33 in broader list</Text>
              <Text component="li" mb={8}>Focus on collaboration patterns, not specific platform features</Text>
              <Text component="li" mb={8}>Share insights about what makes collaboration work</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Engagement Strategy:</Text>
              <Text component="li" mb={8}>Ask for specific challenges, not general thoughts</Text>
              <Text component="li" mb={8}>Offer concrete next steps (group discussion)</Text>
              <Text component="li" mb={8}>Create space for peer-to-peer connection</Text>
              <Text component="li" mb={8}>Invite co-creation, not consumption</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Follow-up Plan:</Text>
              <Text component="li" mb={8}>Respond authentically to every comment</Text>
              <Text component="li" mb={8}>Share follow-up resources based on discussion themes</Text>
              <Text component="li" mb={8}>Connect people with similar challenges privately  </Text>
              <Text component="li" mb={8}>Create recurring monthly "roadmap collaboration check-ins"</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>#ProductManagement #PMCommunity #Collaboration #ProductStrategy #RoadmapPlanning #PeerLearning</Text>
            </div>
          </Container>
        </Box>

        {/* CTA Section */}
        <Box py={96} style={{ background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' }}>
          <Container size="md">
            <Card 
              shadow="xl" 
              radius="xl" 
              p={64}
              style={{ 
                backgroundColor: 'rgba(255, 255, 255, 0.95)',
                textAlign: 'center'
              }}
            >
              <Stack align="center" gap={32}>
                <Stack align="center" gap={16}>
                  <Badge size="lg" color="indigo" variant="light">
                    🚀 Ready to Transform?
                  </Badge>
                  <Title order={2} size="h2" c="dark">
                    Start Your AI-Powered PM Journey Today
                  </Title>
                  <Text size="lg" c="dimmed" maw={500}>
                    Join 500+ product managers who've transformed their workflow with PM33's strategic intelligence platform.
                  </Text>
                </Stack>
                
                <Group gap={24}>
                  <Button
                    component={Link}
                    href="/pricing"
                    size="xl"
                    rightSection={<IconArrowRight size={20} />}
                    style={{ 
                      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                      minWidth: 220,
                      fontWeight: 600
                    }}
                  >
                    Start Free Trial
                  </Button>
                  <Button
                    component={Link}
                    href="/strategic-intelligence"
                    size="xl"
                    variant="outline"
                    color="dark"
                    rightSection={<IconSparkles size={20} />}
                    style={{ minWidth: 180 }}
                  >
                    See Live Demo
                  </Button>
                </Group>
                
                <Text size="sm" c="dimmed">
                  14-day free trial • No credit card required • Cancel anytime
                </Text>
              </Stack>
            </Card>
          </Container>
        </Box>

      </Box>
    </div>
  );
}