'use client';

import React from 'react';
import { Container, Title, Text, Button, Card, Stack, Group, Box, Badge } from '@mantine/core';
import { IconArrowRight, IconSparkles } from '@tabler/icons-react';
import Link from 'next/link';

/**
 * Generated by PM33 Content Factory
 * Source: pm33-demo-comparison-script
 * Generated: 2025-08-24
 */

export default function YoutubeVideoScriptpm33VsTraditionalPmTools10MinuteDemoThatllChangeHowYouWorkPage() {
  return (
    <div className="marketing-context">
      <Box style={{ minHeight: '100vh', backgroundColor: 'var(--mantine-color-gray-0)' }}>
        
        {/* Hero Section */}
        <Box 
          style={{ 
            position: 'relative',
            padding: '4rem 0',
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            overflow: 'hidden',
            color: 'white'
          }}
        >
          <Container size="xl">
            <Stack align="center" gap={32}>
              <Badge 
                size="lg" 
                variant="light"
                color="white"
                leftSection={<IconSparkles size={16} />}
              >
                Video Guides
              </Badge>
              
              <Stack align="center" gap={24}>
                <Title 
                  order={1} 
                  size="3rem"
                  ta="center"
                  lh={1.1}
                  style={{ 
                    fontWeight: 900,
                    color: 'white',
                    maxWidth: 900,
                    textShadow: '0 2px 4px rgba(0,0,0,0.1)'
                  }}
                >
                  YouTube Video Script: "PM33 vs Traditional PM Tools: 10-Minute Demo That'll Change How You Work"
                </Title>
                
                <Text size="xl" ta="center" maw={700} lh={1.6} style={{ opacity: 0.95 }}>
                  - Screen recordings of PM33 interface
                </Text>

                <Group gap={24} mt={32}>
                  <Button 
                    component={Link}
                    href="/pricing"
                    size="xl"
                    variant="white"
                    color="dark"
                    rightSection={<IconArrowRight size={20} />}
                    style={{ 
                      minWidth: 200,
                      fontWeight: 600
                    }}
                  >
                    Start Free Trial
                  </Button>
                  <Button 
                    component={Link}
                    href="/strategic-intelligence"
                    size="xl"
                    variant="outline"
                    color="white"
                    rightSection={<IconSparkles size={20} />}
                    style={{ minWidth: 180 }}
                  >
                    See Live Demo
                  </Button>
                </Group>
              </Stack>
            </Stack>
          </Container>
        </Box>

        {/* Content Section */}
        <Box py={96} bg="white">
          <Container size="xl">
            <div className="content-factory-article" style={{
              fontSize: '18px',
              lineHeight: '1.7',
              color: 'var(--mantine-color-dark-8)'
            }}>
              <Title order={1} size="2.5rem" mb={24} c="dark">YouTube Video Script: "PM33 vs Traditional PM Tools: 10-Minute Demo That'll Change How You Work"</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>Video Length:</Text> 8-12 minutes
              <Text component="span" fw={700}>Target Audience:</Text> Product managers researching AI PM tools
              <Text component="span" fw={700}>Goal:</Text> Demonstrate PM33's unique value proposition with clear before/after comparison
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Pre-Production Notes</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>Visual Elements Needed:</Text>
              <Text component="li" mb={8}>Screen recordings of PM33 interface  </Text>
              <Text component="li" mb={8}>Comparison screenshots of Jira, Monday.com, Productboard</Text>
              <Text component="li" mb={8}>Before/after workflow diagrams</Text>
              <Text component="li" mb={8}>ROI charts and productivity metrics</Text>
              <Text component="li" mb={8}>Customer testimonial clips (text overlays if no video)</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Tone:</Text> Professional but conversational, confident without being pushy
              <Text component="span" fw={700}>Pacing:</Text> Quick enough to maintain attention, slow enough for comprehension
              <Text component="span" fw={700}>CTA Strategy:</Text> Multiple soft CTAs throughout, strong CTA at end
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">HOOK (0:00-0:15)</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Split screen showing frustrated PM vs empowered PM with AI]</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Narrator (energetic):</Text> "If you're a product manager spending 60-80% of your time writing PRDs, synthesizing feedback, and creating status reports instead of building strategy, this 10-minute demo will change everything."
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: PM33 logo animation]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"I'm going to show you PM33 - the AI tool that makes your existing PM stack 10x smarter without forcing you to migrate anything. And by the end, you'll see exactly why 2,500+ product teams chose enhancement over replacement."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Quick montage of PM33 in action]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Let's dive in."</Text>
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">PROBLEM SETUP (0:15-1:30)</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Typical PM desktop with multiple tools open - Jira, Slack, Sheets, etc.]</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Narrator:</Text> "Here's what most PM workflows look like: Data scattered across Jira, Slack, Monday.com, Google Sheets, Zendesk, and five other tools. Sound familiar?"
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Time-lapse simulation of PM switching between tools]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"You're constantly switching between tools, manually copying data, and trying to piece together insights from fragments of information. A simple feature prioritization decision requires:"</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Checklist appearing with each item]</Text>
              <Text component="li" mb={8}>"Reviewing 200+ customer feedback messages"</Text>
              <Text component="li" mb={8}>"Analyzing sprint velocity across three different dashboards" </Text>
              <Text component="li" mb={8}>"Manually writing user stories and acceptance criteria"</Text>
              <Text component="li" mb={8}>"Creating executive summaries from scratch"</Text>
              <Text component="li" mb={8}>"Updating stakeholders across multiple channels"</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Clock showing time elapsed - 4 hours]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Four hours later, you've made one prioritization decision. Meanwhile, your competitors with AI-enhanced workflows made 10."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Competitor progress bar racing ahead]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"The traditional solutions? Replace everything with a 'comprehensive' platform, spend 3-6 months migrating, retrain your entire team, and hope the new tool is actually better than what you had."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Migration timeline showing months of disruption]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"There's a better way."</Text>
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">SOLUTION INTRODUCTION (1:30-2:45)</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: PM33 interface appearing like an AI overlay on existing tools]</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Narrator:</Text> "Meet PM33. Instead of replacing your PM tools, it makes them AI-powered. Think of it as an AI brain that connects to everything you're already using."
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Connection lines showing PM33 linking to Jira, Slack, Monday, etc.]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Here's what makes PM33 different from every other AI PM tool:"</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Three-column comparison: Replace, Add-on, Enhance]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"While other tools make you choose between replacing your entire workflow or getting basic AI features, PM33 gives you strategic AI intelligence that works with your existing stack."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: PM33 dashboard with insights from multiple tools]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"You keep using Jira, Monday.com, Asana, Slack - whatever works for your team. But now they're connected by an AI that thinks like a senior product manager."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Before/after split screen of same workflow]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Let me show you exactly what this looks like."</Text>
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">LIVE DEMO SECTION 1: CROSS-PLATFORM INTELLIGENCE (2:45-4:30)</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Screen recording of PM33 interface]</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Narrator:</Text> "This is PM33's main dashboard. Notice it's not trying to be another project management tool. Instead, it's synthesizing data from everywhere."
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Data flowing in from different connected tools]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Here's the magic: PM33 has analyzed 847 Jira tickets, 23 customer interviews from Slack, 156 support tickets from Zendesk, and our latest user research. Instead of me spending hours connecting these dots manually..."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: AI analysis happening in real-time]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"PM33's AI immediately identifies that mobile performance issues are mentioned in 34% of support tickets, correlate with a 23% increase in churn, and appear in sprint retrospectives as a recurring blocker."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Insight appearing with supporting data points]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"But here's the strategic part - it doesn't just tell me what's happening. It tells me what to do about it."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: AI recommendation panel opening]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"'Based on historical data, prioritizing mobile performance optimization would reduce churn by an estimated 34% and increase customer satisfaction by 0.8 points. Recommended timeline: 2 sprints. Here are the specific technical requirements and user stories to get started.'"</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Generated PRD and user stories]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"This insight would have taken me 4-6 hours to compile manually. PM33 generated it in 30 seconds, and it's more comprehensive than what I would have created on my own."</Text>
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">LIVE DEMO SECTION 2: AUTOMATED DOCUMENTATION (4:30-6:00)</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: New feature request coming in through Slack]</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Narrator:</Text> "Let's see document generation in action. Here's a feature request that just came in: 'Users want better onboarding flow - current drop-off is too high.'"
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Typing the brief description into PM33]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Instead of spending 3-4 hours writing a comprehensive PRD, watch this."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: AI generating complete documentation in real-time]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"PM33 is creating:"</Text>
              <Text component="li" mb={8}>"Complete PRD with problem statement, user personas, and success metrics"</Text>
              <Text component="li" mb={8}>"Epic breakdown with 8 user stories and acceptance criteria" </Text>
              <Text component="li" mb={8}>"Technical requirements based on our existing architecture"</Text>
              <Text component="li" mb={8}>"Testing scenarios including edge cases"</Text>
              <Text component="li" mb={8}>"Implementation timeline with dependencies"</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Document appearing fully formatted]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Five minutes. That's what used to take me half a day, and it's formatted exactly how our team expects. But the AI doesn't just generate generic content - it's learned our team's patterns, terminology, and standards."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Highlighting team-specific elements in the generated content]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Notice it referenced our specific onboarding metrics, used our standard user story format, and even included our accessibility requirements without me asking."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Side-by-side comparison with manually written PRD]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"This isn't replacing human thinking - it's handling the routine work so I can focus on the strategic decisions."</Text>
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">COMPETITOR COMPARISON (6:00-7:15)</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Comparison table appearing]</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Narrator:</Text> "Now, let's address the elephant in the room. How does this compare to other AI PM tools?"
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Screenshots of ChatPRD, Productboard AI, ClickUp AI]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"ChatPRD excels at document generation but requires you to manage everything else manually. Productboard AI has great customer feedback features but costs $25-74 per user and requires full migration. ClickUp AI gives you project management plus AI, but you're starting from scratch."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Migration timeline comparison]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Here's the reality check: ChatPRD takes 2-4 weeks to implement effectively. Productboard migration typically takes 4-8 weeks. ClickUp setup ranges from 2-6 weeks depending on complexity."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: PM33 setup animation]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"PM33? You're productive in hours. Because you're not changing your workflow - you're supercharging it."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Cost comparison chart]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Cost-wise, PM33's usage-based pricing means you pay for value, not seats. A 10-person team using PM33 Professional costs $3,600 annually versus $6,000-8,800 for Productboard or $2,000-3,000 for ClickUp plus AI add-ons."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: ROI calculation]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"But here's what matters: PM33 customers report 60-80% time savings on routine work. For our 10-person team example, that's equivalent to gaining 6-8 additional PMs worth of strategic capacity."</Text>
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">CUSTOMER SUCCESS STORY (7:15-8:00)</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Customer testimonial text overlay with company logos]</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Narrator:</Text> "Don't just take my word for it. Sarah Chen, Head of Product at TechFlow, told us:"
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Quote animation]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"'PM33's AI handles all our routine documentation and analysis. Our PMs now spend 3x more time on customer research and strategic planning. We shipped 40% more features without hiring additional PMs. Game-changer for our product velocity.'"</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Before/after metrics for TechFlow]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"TechFlow saw results in their first month: 68% time savings on routine work, 42% increase in feature velocity, and ROI payback in just 3 weeks."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Multiple customer logos and metrics]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"This isn't a one-off result. Across 2,500+ teams using PM33, the average impact is 60-80% time savings and 40%+ increase in strategic output."</Text>
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">CALL TO ACTION (8:00-8:45)</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: PM33 trial signup page]</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Narrator:</Text> "Ready to transform your PM workflow? Here's how to get started:"
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Three-step process animation]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"First, sign up for PM33's free 14-day trial - no credit card required. Second, connect your existing tools - takes about 10 minutes. Third, start using AI-powered insights while keeping your familiar workflow."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Guarantee badge]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"PM33 comes with a '10x Time Saved' guarantee. If you don't save significant time on routine PM work within 30 days, you get a full refund."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Multiple CTA options]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Click the link in the description to start your free trial, or visit pm33.ai to book a personalized demo with your actual data."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: PM33 logo with tagline]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Don't replace your PM tools - make them 10x smarter with PM33."</Text>
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">END SCREEN (8:45-9:00)</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Subscribe animation with related video thumbnails]</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Narrator:</Text> "If this video helped you understand AI project management better, hit subscribe for more product management insights. Check out our comparison of the top 10 AI PM tools, or watch our deep dive into AI-powered feature prioritization."
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Related video clickable thumbnails]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Questions about PM33 or AI in product management? Drop them in the comments - I respond to every single one."</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>[Visual: Final CTA overlay]</Text>
              <Box mb={16} />
              <Text mb={16} lh={1.7}>"Link to free trial is in the description. Thanks for watching!"</Text>
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Video Description Template</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>Title:</Text> PM33 vs Traditional PM Tools: 10-Minute Demo That'll Change How You Work
              <Box mb={16} />
              <Text component="span" fw={700}>Description:</Text>
              <Text mb={16} lh={1.7}>Are you tired of spending 60-80% of your PM time on admin work instead of strategy? This demo shows how PM33 transforms your existing PM workflow with AI - no migration required.</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>What you'll see:</Text>
              <Text mb={16} lh={1.7}>✅ Live demo of AI cross-platform intelligence</Text>
              <Text mb={16} lh={1.7}>✅ Real-time document generation (PRD in 5 minutes)</Text>
              <Text mb={16} lh={1.7}>✅ Head-to-head comparison with ChatPRD, Productboard, ClickUp</Text>
              <Text mb={16} lh={1.7}>✅ Actual customer results and ROI metrics</Text>
              <Text mb={16} lh={1.7}>✅ How to get started in minutes, not months</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Key timestamps:</Text>
              <Text mb={16} lh={1.7}>0:15 - The PM productivity problem</Text>
              <Text mb={16} lh={1.7}>2:45 - PM33 live demo begins</Text>
              <Text mb={16} lh={1.7}>4:30 - Automated documentation in action</Text>
              <Text mb={16} lh={1.7}>6:00 - Competitor comparison</Text>
              <Text mb={16} lh={1.7}>7:15 - Customer success story</Text>
              <Text mb={16} lh={1.7}>8:00 - How to get started</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Ready to 10x your PM productivity?</Text>
              <Text mb={16} lh={1.7}>🔗 Free 14-day trial (no credit card): https://pm33.ai/trial</Text>
              <Text mb={16} lh={1.7}>🔗 Book personalized demo: https://pm33.ai/demo</Text>
              <Text mb={16} lh={1.7}>🔗 Complete PM tool comparison: https://pm33.ai/compare</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Tags:</Text> #ProductManagement #AITools #ProductManager #PMSoftware #ProductStrategy #AIProductManager #TechDemo #SaaS #Productivity
              <Box mb={16} />
              <Box my={32}><div style={{ height: "1px", background: "var(--mantine-color-gray-3)" }} /></Box>
              <Box mb={16} />
              <Title order={2} size="2rem" mb={20} c="dark">Production Notes</Title>
              <Box mb={16} />
              <Text component="span" fw={700}>Visual Requirements:</Text>
              <Text component="li" mb={8}>High-quality screen recordings with cursor highlighting</Text>
              <Text component="li" mb={8}>Clean, professional interface shots</Text>
              <Text component="li" mb={8}>Smooth transitions between demo sections</Text>
              <Text component="li" mb={8}>Clear, readable text overlays for statistics</Text>
              <Text component="li" mb={8}>Consistent branding throughout</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Audio Requirements:</Text>
              <Text component="li" mb={8}>Clear narration with professional microphone</Text>
              <Text component="li" mb={8}>Background music (subtle, non-distracting)</Text>
              <Text component="li" mb={8}>Sound effects for transitions and emphasis points</Text>
              <Text component="li" mb={8}>Consistent audio levels throughout</Text>
              <Box mb={16} />
              <Text component="span" fw={700}>Editing Notes:</Text>
              <Text component="li" mb={8}>Keep pace brisk but allow time for information absorption</Text>
              <Text component="li" mb={8}>Use jump cuts to eliminate dead time</Text>
              <Text component="li" mb={8}>Add visual emphasis (circles, arrows) for key points</Text>
              <Text component="li" mb={8}>Include captions for accessibility</Text>
              <Text component="li" mb={8}>Optimize for mobile viewing (large text, clear visuals)</Text>
            </div>
          </Container>
        </Box>

        {/* CTA Section */}
        <Box py={96} style={{ background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' }}>
          <Container size="md">
            <Card 
              shadow="xl" 
              radius="xl" 
              p={64}
              style={{ 
                backgroundColor: 'rgba(255, 255, 255, 0.95)',
                textAlign: 'center'
              }}
            >
              <Stack align="center" gap={32}>
                <Stack align="center" gap={16}>
                  <Badge size="lg" color="indigo" variant="light">
                    🚀 Ready to Transform?
                  </Badge>
                  <Title order={2} size="h2" c="dark">
                    Start Your AI-Powered PM Journey Today
                  </Title>
                  <Text size="lg" c="dimmed" maw={500}>
                    Join 500+ product managers who've transformed their workflow with PM33's strategic intelligence platform.
                  </Text>
                </Stack>
                
                <Group gap={24}>
                  <Button
                    component={Link}
                    href="/pricing"
                    size="xl"
                    rightSection={<IconArrowRight size={20} />}
                    style={{ 
                      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                      minWidth: 220,
                      fontWeight: 600
                    }}
                  >
                    Start Free Trial
                  </Button>
                  <Button
                    component={Link}
                    href="/strategic-intelligence"
                    size="xl"
                    variant="outline"
                    color="dark"
                    rightSection={<IconSparkles size={20} />}
                    style={{ minWidth: 180 }}
                  >
                    See Live Demo
                  </Button>
                </Group>
                
                <Text size="sm" c="dimmed">
                  14-day free trial • No credit card required • Cancel anytime
                </Text>
              </Stack>
            </Card>
          </Container>
        </Box>

      </Box>
    </div>
  );
}