name: PM33 Development Coordination - Multi-AI Testing Framework
on:
  push:
    branches: [ main, develop ]
    paths: [ '.github/**', 'scripts/**', 'docs/**', 'pm33-orchestration/**' ]
  pull_request:
    branches: [ main ]
    paths: [ '.github/**', 'pm33-orchestration/**' ]
  schedule:
    # Run daily at 2 AM UTC to catch API changes
    - cron: '0 2 * * *'

env:
  PYTHON_VERSION: '3.11'
  CORE_APP_REPO: 'b33-steve/pm33-core-app'

jobs:
  prepare-multi-ai-testing:
    name: 🧠 Prepare Multi-AI Testing Framework for Core App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Test Anthropic Claude Connection
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python -c "
          import anthropic
          client = anthropic.Anthropic(api_key='$ANTHROPIC_API_KEY')
          response = client.messages.create(
              model='claude-3-sonnet-20240229',
              max_tokens=100,
              messages=[{'role': 'user', 'content': 'Health check: respond with OK'}]
          )
          print('✅ Anthropic Claude connection: OK')
          assert 'OK' in response.content[0].text
          "
          
      - name: Test OpenAI Connection
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -c "
          import openai
          client = openai.OpenAI(api_key='$OPENAI_API_KEY')
          response = client.chat.completions.create(
              model='gpt-4',
              max_tokens=100,
              messages=[{'role': 'user', 'content': 'Health check: respond with OK'}]
          )
          print('✅ OpenAI connection: OK')
          assert 'OK' in response.choices[0].message.content
          "
          
      - name: Test Together AI Connection
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        run: |
          python -c "
          import together
          client = together.Together(api_key='$TOGETHER_API_KEY')
          response = client.chat.completions.create(
              model='meta-llama/Llama-2-7b-chat-hf',
              max_tokens=100,
              messages=[{'role': 'user', 'content': 'Health check: respond with OK'}]
          )
          print('✅ Together AI connection: OK')
          assert 'OK' in response.choices[0].message.content
          "

  ai-orchestration-tests:
    name: Multi-AI Orchestration Tests
    runs-on: ubuntu-latest
    needs: ai-service-health
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio
          
      - name: Test Strategic Intelligence AI Team
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
        run: |
          python -c "
          print('🧠 Testing Strategic Intelligence AI Team...')
          # Test Claude + Pinecone + PostHog integration
          import sys
          sys.path.append('.')
          from app.backend.services.ai_team_orchestrator import StrategicIntelligenceTeam
          
          team = StrategicIntelligenceTeam()
          result = team.analyze_strategic_question(
              'Should we hire 5 engineers or invest $200K in marketing?',
              company_context={'stage': 'series_a', 'team_size': 25}
          )
          
          assert result['analysis'] is not None
          assert result['framework_reasoning'] is not None
          assert result['confidence_score'] > 0.5
          print('✅ Strategic Intelligence AI Team: Working')
          "
          
      - name: Test Workflow Execution AI Team
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          python -c "
          print('⚡ Testing Workflow Execution AI Team...')
          # Test OpenAI + Railway + PM Tool APIs integration
          import sys
          sys.path.append('.')
          from app.backend.services.ai_team_orchestrator import WorkflowExecutionTeam
          
          team = WorkflowExecutionTeam()
          result = team.generate_executable_workflow(
              strategic_decision='Launch European market expansion',
              timeline_months=6
          )
          
          assert result['workflow_steps'] is not None
          assert len(result['workflow_steps']) > 3
          assert result['timeline'] is not None
          print('✅ Workflow Execution AI Team: Working')
          "
          
      - name: Test Data Intelligence AI Team
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          python -c "
          print('📊 Testing Data Intelligence AI Team...')
          # Test Together AI + Pinecone + Railway integration
          import sys
          sys.path.append('.')
          from app.backend.services.ai_team_orchestrator import DataIntelligenceTeam
          
          team = DataIntelligenceTeam()
          result = team.analyze_company_patterns(
              company_id='test-company',
              analysis_type='performance_trends'
          )
          
          assert result['insights'] is not None
          assert result['predictions'] is not None
          assert result['confidence_score'] > 0.3
          print('✅ Data Intelligence AI Team: Working')
          "
          
      - name: Test Communication AI Team
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          python -c "
          print('📢 Testing Communication AI Team...')
          # Test Claude/OpenAI + Resend + Railway integration  
          import sys
          sys.path.append('.')
          from app.backend.services.ai_team_orchestrator import CommunicationTeam
          
          team = CommunicationTeam()
          result = team.generate_stakeholder_communication(
              strategic_decision='Delay product launch by 2 months',
              stakeholder_type='executive_team',
              communication_type='status_update'
          )
          
          assert result['communication_text'] is not None
          assert len(result['communication_text']) > 100
          assert result['tone_analysis']['confidence'] > 0.7
          print('✅ Communication AI Team: Working')
          "

  performance-benchmarks:
    name: AI Performance Benchmarks
    runs-on: ubuntu-latest
    needs: ai-orchestration-tests
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-benchmark
          
      - name: Benchmark Strategic Analysis Speed
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        run: |
          python -c "
          import time
          import sys
          sys.path.append('.')
          
          print('⏱️ Benchmarking AI response times...')
          
          # Target: Strategic analysis under 10 seconds
          start_time = time.time()
          # Simulate strategic analysis request
          from pm33_multi_engine_demo import analyze_strategic_question
          
          result = analyze_strategic_question(
              'Our competitor raised $50M. Strategic response?',
              engine='together_ai'  # Cost-effective for benchmarking
          )
          
          response_time = time.time() - start_time
          
          print(f'📊 Strategic analysis response time: {response_time:.2f}s')
          
          # Fail if response time exceeds 10 seconds
          assert response_time < 10.0, f'Response time {response_time:.2f}s exceeds 10s target'
          
          print('✅ Performance benchmark: PASSED')
          print(f'🎯 Target <10s: {response_time:.2f}s (PMO-level speed achieved)')
          "
          
      - name: Validate Success Rate Metrics
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        run: |
          python -c "
          print('🎯 Validating success rate metrics...')
          
          # Test multiple strategic questions for consistency
          success_count = 0
          total_tests = 5
          
          test_questions = [
              'Should we hire engineers or invest in marketing?',
              'How do we respond to competitive threat?',
              'What is optimal pricing strategy?',
              'Should we expand to European market?',
              'How do we improve retention by 15%?'
          ]
          
          import sys
          sys.path.append('.')
          from pm33_multi_engine_demo import analyze_strategic_question
          
          for question in test_questions:
              try:
                  result = analyze_strategic_question(question, engine='together_ai')
                  
                  # Validate response quality
                  if (result and 
                      len(result.get('analysis', '')) > 200 and
                      result.get('confidence', 0) > 0.6):
                      success_count += 1
                      print(f'✅ Question passed quality check')
                  else:
                      print(f'⚠️ Question failed quality check')
                      
              except Exception as e:
                  print(f'❌ Question failed with error: {e}')
          
          success_rate = (success_count / total_tests) * 100
          print(f'📈 Success Rate: {success_rate}% ({success_count}/{total_tests})')
          
          # Target: >85% strategic success rate
          assert success_rate >= 85.0, f'Success rate {success_rate}% below 85% target'
          
          print('✅ Success rate validation: PASSED')
          print('🏆 PM33 delivering PMO-level strategic intelligence')
          "

  failover-testing:
    name: AI Service Failover Tests
    runs-on: ubuntu-latest
    needs: performance-benchmarks
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Test AI Service Failover
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        run: |
          python -c "
          print('🔄 Testing AI service failover mechanisms...')
          
          import sys
          sys.path.append('.')
          from pm33_multi_engine_demo import analyze_strategic_question
          
          # Test failover from primary to secondary AI service
          try:
              # Simulate primary service failure by using invalid API key temporarily
              result = analyze_strategic_question(
                  'Test failover question',
                  engine='anthropic',
                  fallback_enabled=True
              )
              
              assert result is not None, 'Failover mechanism failed'
              print('✅ AI service failover: Working correctly')
              
          except Exception as e:
              print(f'❌ Failover test failed: {e}')
              raise
          
          print('🛡️ Multi-AI orchestration resilience: VERIFIED')
          "

  deployment-readiness:
    name: Deployment Readiness Check
    runs-on: ubuntu-latest
    needs: [ai-orchestration-tests, performance-benchmarks, failover-testing]
    steps:
      - name: ✅ Multi-AI Backend Validation Complete
        run: |
          echo "🚀 PM33 Multi-AI Backend: ALL SYSTEMS GO"
          echo ""
          echo "✅ All 4 Agentic AI Teams operational:"
          echo "   🧠 Strategic Intelligence AI Team (Claude + Pinecone + PostHog)"
          echo "   ⚡ Workflow Execution AI Team (OpenAI + Railway + PM Tool APIs)"
          echo "   📊 Data Intelligence AI Team (Together AI + Pinecone + Railway)"
          echo "   📢 Communication AI Team (Claude/OpenAI + Resend + Railway)"
          echo ""
          echo "🎯 Performance Targets Met:"
          echo "   ⏱️ Strategic analysis <10 seconds"
          echo "   📈 Success rate >85%"
          echo "   🔄 Multi-AI failover working"
          echo "   🛡️ Service resilience verified"
          echo ""
          echo "💰 Ready to support $100K MRR through PMO transformation"
          echo "🏆 Individual PMs → PMO capabilities: DELIVERED"